# Generated by Django 5.1.4 on 2026-06-21 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('troupe', models.CharField(blank=True, default='', max_length=128)),
                ('genre', models.CharField(choices=[('concert', '演唱会'), ('drama', '话剧'), ('musical', '音乐剧'), ('opera', '戏曲'), ('other', '其他')], default='concert', max_length=16)),
                ('status', models.CharField(choices=[('on_sale', '售票中'), ('upcoming', '待开票'), ('ended', '已结束')], default='upcoming', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.hall')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.show')),
            ],
            options={
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='SeatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=32)),
                ('row', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=8)),
                ('grade', models.CharField(choices=[('VIP', 'VIP'), ('A', 'A'), ('B', 'B')], default='B', max_length=8)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_templates', to='tickets.hall')),
            ],
            options={
                'db_table': 'seat_templates',
                'unique_together': {('hall', 'zone', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=32)),
                ('row', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=8)),
                ('grade', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', '可售'), ('locked', '锁定'), ('sold', '已售')], default='available', max_length=16)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tickets.performance')),
                ('seat_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.seattemplate')),
            ],
            options={
                'db_table': 'performance_seats',
                'unique_together': {('performance', 'seat_template')},
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.performance')),
            ],
            options={
                'db_table': 'ticket_orders',
            },
        ),
        migrations.CreateModel(
            name='PerformanceSeatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_prices', to='tickets.performance')),
            ],
            options={
                'db_table': 'performance_seat_prices',
                'unique_together': {('performance', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='OrderSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.performanceseat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seats', to='tickets.ticketorder')),
            ],
            options={
                'db_table': 'order_seats',
                'unique_together': {('order', 'performance_seat')},
            },
        ),
    ]
